/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "common_macros.h"

#define RCC_BASE         0x40021000
#define portA_BASE       0x40010800

#define RCC_APB2ENR      *((volatile uint32_t *) (RCC_BASE   + 0x18))
#define GPIOA_CRH        *((volatile uint32_t *) (portA_BASE + 0x04))
#define GPIOA_ODR        *((volatile uint32_t *) (RCC_BASE   + 0x0C))
#define RCC_APB2ENR      *((volatile uint32_t *) (RCC_BASE   + 0x18))
 int main(void)
{
     SET_BIT(RCC_APB2ENR, 2); 
     GPIOA_CRH &= 0xff0fffff;
     GPIOA_CRH |= 0x00200000;
     while (1)
     {
         
         
         SET_BIT(GPIOA_ODR, 13);
         for(uint32_t i = 0; i < 5000; i++);
         SET_BIT(GPIOA_ODR, 13);
         for(uint32_t i = 0; i < 5000; i++);
         
     }
     return 0;
}
